export // Realistic planet data with fallback colors
const planetData = [
  {
    name: "Mercury",
    size: 0.4,
    distance: 8,
    orbitalPeriod: 88,
    rotationPeriod: 58.6,
    eccentricity: 0.206,
    inclination: 7.0,
    color: "#8C7853",
    emissive: "#2C1810",
    info: "Closest to the Sun, extreme temperatures",
    facts: [
      "No atmosphere",
      "Heavily cratered",
      "Iron core makes up 75% of radius",
    ],
  },
  {
    name: "Venus",
    size: 0.95,
    distance: 12,
    orbitalPeriod: 225,
    rotationPeriod: -243,
    eccentricity: 0.007,
    inclination: 3.4,
    color: "#FFC649",
    emissive: "#332810",
    info: "Hottest planet, thick atmosphere",
    facts: ["Surface temp: 462°C", "Retrograde rotation", "Volcanic activity"],
  },
  {
    name: "Earth",
    size: 1.0,
    distance: 16,
    orbitalPeriod: 365,
    rotationPeriod: 1,
    eccentricity: 0.017,
    inclination: 0.0,
    color: "#6B93D6",
    emissive: "#0A1A2E",
    info: "Our home planet, perfect for life",
    facts: [
      "71% water coverage",
      "Only known planet with life",
      "One natural satellite",
    ],
  },
  {
    name: "Mars",
    size: 0.53,
    distance: 22,
    orbitalPeriod: 687,
    rotationPeriod: 1.03,
    eccentricity: 0.094,
    inclination: 1.9,
    color: "#CD5C5C",
    emissive: "#2D0A0A",
    info: "The Red Planet, potential for past life",
    facts: [
      "Largest volcano: Olympus Mons",
      "Two small moons",
      "Polar ice caps",
    ],
  },
  {
    name: "Jupiter",
    size: 2.5,
    distance: 32,
    orbitalPeriod: 4333,
    rotationPeriod: 0.41,
    eccentricity: 0.049,
    inclination: 1.3,
    color: "#D2691E",
    emissive: "#2D1A05",
    info: "Largest planet, gas giant",
    facts: [
      "Great Red Spot storm",
      "79 known moons",
      "Mostly hydrogen and helium",
    ],
  },
  {
    name: "Saturn",
    size: 2.1,
    distance: 42,
    orbitalPeriod: 10759,
    rotationPeriod: 0.45,
    eccentricity: 0.057,
    inclination: 2.5,
    color: "#FAD5A5",
    emissive: "#2D2415",
    info: "Beautiful ring system, gas giant",
    facts: ["Prominent ring system", "82 known moons", "Less dense than water"],
  },
  {
    name: "Uranus",
    size: 1.6,
    distance: 52,
    orbitalPeriod: 30687,
    rotationPeriod: -0.72,
    eccentricity: 0.046,
    inclination: 0.8,
    color: "#4FD0E7",
    emissive: "#0A2D33",
    info: "Ice giant, tilted on its side",
    facts: ["Rotates on its side", "Faint ring system", "27 known moons"],
  },
  {
    name: "Neptune",
    size: 1.5,
    distance: 62,
    orbitalPeriod: 60190,
    rotationPeriod: 0.67,
    eccentricity: 0.01,
    inclination: 1.8,
    color: "#4169E1",
    emissive: "#0A0F2D",
    info: "Windiest planet, ice giant",
    facts: [
      "Fastest winds: 2,100 km/h",
      "14 known moons",
      "Deep blue color from methane",
    ],
  },
];
